apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: kata-bare-metal
spec:
  template:
    metadata:
      labels:
        katacontainers.io/kata-runtime: "true"
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: kata-bare-metal
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            {{- range .Values.instanceTypes }}
            - {{ . }}
            {{- end }}
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
      taints:
        - key: kata
          value: "true"
          effect: NoSchedule
  limits:
    cpu: {{ .Values.nodePool.cpuLimit | quote }}
    memory: {{ .Values.nodePool.memoryLimit | quote }}
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: {{ .Values.nodePool.consolidateAfter }}
