FROM node:22-alpine
WORKDIR /app
ENV NODE_ENV=production
RUN addgroup -g 1001 nodejs && adduser -S -u 1001 -G nodejs nextjs
COPY --chown=nextjs:nodejs .next ./.next
COPY --chown=nextjs:nodejs node_modules ./node_modules
COPY --chown=nextjs:nodejs public ./public
COPY --chown=nextjs:nodejs package.json ./package.json
USER 1001
EXPOSE 3000
CMD ["npm", "start"]
