apiVersion: v2
name: openclaw
description: OpenClaw operator
type: application
version: 0.1.0
dependencies:
  - name: openclaw-operator
    version: "0.36.5"
    repository: oci://ghcr.io/paperclipinc/charts
