#!/usr/bin/env bash
# Full deploy: Packer → Terraform (EKS + Karpenter + ArgoCD) → GitOps
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
TERRAFORM_DIR="${ROOT_DIR}/terraform"
PACKER_DIR="${ROOT_DIR}/packer"

# ---------------- Pre-flight ----------------

echo "==> Checking prerequisites..."
for bin in terraform packer kubectl aws git; do
  command -v "$bin" >/dev/null 2>&1 || { echo "ERROR: $bin not on PATH"; exit 1; }
done

if [ ! -f "${TERRAFORM_DIR}/terraform.tfvars" ]; then
  echo "ERROR: terraform/terraform.tfvars not found."
  echo "Copy the example and fill in your values:"
  echo "  cp terraform/terraform.tfvars.example terraform/terraform.tfvars"
  exit 1
fi

GITOPS_REPO_URL=$(grep '^gitops_repo_url' "${TERRAFORM_DIR}/terraform.tfvars" | sed 's/.*= *"\(.*\)"/\1/' || true)
if [ -z "${GITOPS_REPO_URL}" ]; then
  echo "ERROR: gitops_repo_url not set in terraform.tfvars"
  exit 1
fi

REGION=$(grep '^region' "${TERRAFORM_DIR}/terraform.tfvars" 2>/dev/null | sed 's/.*= *"\(.*\)"/\1/' || true)
REGION="${REGION:-us-west-2}"

# ---------------- Packer: bake the Kata AMI (once, cached in .auto.tfvars) ----------------

AUTO_TFVARS="${TERRAFORM_DIR}/terraform.auto.tfvars"
EXISTING_AMI=""
if [ -f "${AUTO_TFVARS}" ]; then
  EXISTING_AMI=$(grep '^kata_ami_id' "${AUTO_TFVARS}" 2>/dev/null | sed 's/.*= *"\(.*\)"/\1/' || true)
fi

FORCE_REBAKE=$(grep '^force_rebake' "${TERRAFORM_DIR}/terraform.tfvars" 2>/dev/null | sed 's/.*= *\(true\|false\).*/\1/' || echo "false")

if [ -n "${EXISTING_AMI}" ] && [ "${FORCE_REBAKE}" != "true" ]; then
  echo "==> Reusing cached Kata AMI: ${EXISTING_AMI}"
  echo "    (set force_rebake=true in terraform.tfvars to rebuild)"
else
  echo "==> Baking Kata AMI with Packer (takes ~12 min the first time)..."
  cd "${PACKER_DIR}"
  packer init .
  packer build -var "region=${REGION}" -var "source_type=nested" -machine-readable kata-ami.pkr.hcl \
    | tee /tmp/packer-build.log
  # Extract AMI ID from the machine-readable log
  AMI_ID=$(grep 'artifact,0,id' /tmp/packer-build.log | awk -F, '{print $6}' | sed 's/.*://;s/%!.*//' | head -1)
  if [ -z "${AMI_ID}" ]; then
    echo "ERROR: packer build finished but could not parse AMI ID from /tmp/packer-build.log"
    exit 1
  fi
  echo "==> Baked AMI: ${AMI_ID}"
  cat > "${AUTO_TFVARS}" <<EOF
# Auto-generated by scripts/install.sh after packer build.
# Safe to commit; regenerated on force_rebake=true.
kata_ami_id = "${AMI_ID}"
EOF
fi

# ---------------- Terraform apply ----------------

cd "${TERRAFORM_DIR}"
echo "==> Initializing Terraform..."
terraform init -upgrade

echo "==> Applying infrastructure (VPC, EKS, system MNG, Karpenter, ArgoCD, Bedrock Guardrail, Cognito, EFS)..."
terraform apply -auto-approve

CLUSTER_NAME=$(terraform output -raw cluster_name)
echo "==> Updating kubeconfig..."
aws eks update-kubeconfig --region "${REGION}" --name "${CLUSTER_NAME}"

echo "==> Waiting for system nodes to be Ready..."
kubectl wait --for=condition=Ready nodes --all --timeout=300s

# ---------------- GitOps bootstrap ----------------

echo "==> Setting GitOps repo URL in ArgoCD app manifests..."
if [[ "$OSTYPE" == "darwin"* ]]; then
  SED_INPLACE=(-i '')
else
  SED_INPLACE=(-i)
fi
sed "${SED_INPLACE[@]}" "s|GITOPS_REPO_URL_PLACEHOLDER|${GITOPS_REPO_URL}|g" "${ROOT_DIR}/gitops/apps/"*.yaml
git -C "${ROOT_DIR}" add gitops/
git -C "${ROOT_DIR}" diff --cached --quiet || git -C "${ROOT_DIR}" commit -m "chore: set ArgoCD repo URL"
git -C "${ROOT_DIR}" push

# ---------------- Done ----------------

echo ""
echo "==> Deploy complete. ArgoCD will sync all waves from your Git repo."
echo ""
echo "  ArgoCD UI:  kubectl port-forward -n argocd svc/argo-cd-argocd-server 8080:443"
echo "  Grafana UI: kubectl port-forward -n monitoring svc/kube-prometheus-stack-grafana 3000:80"
echo "  Apps:       kubectl get applications -n argocd"
echo "  Sandboxes:  kubectl get sandbox -A"
echo ""
echo "==> OPTIONAL: Create Slack tokens secret for the Slack sandbox agent"
echo ""
echo "    kubectl create secret generic slack-tokens -n openclaw \\"
echo "      --from-literal=bot-token=\"xoxb-...\" \\"
echo "      --from-literal=app-token=\"xapp-...\" \\"
echo "      --from-literal=signing-secret=\"...\""
echo ""
echo "==> OPTIONAL: Render + push the finance-ui deployment (after the first terraform apply)"
echo ""
echo "    ./scripts/render-finance-ui.sh <image-tag>   # e.g. v0.9.7"
echo ""
echo "Outputs:"
echo "  LiteLLM API key:       $(terraform output -raw litellm_api_key 2>/dev/null || echo '(not yet available)')"
echo "  Bedrock Guardrail ID:  $(terraform output -raw bedrock_guardrail_id 2>/dev/null || echo '(not yet available)')"
echo "  Finance UI host:       $(terraform output -raw finance_ui_host 2>/dev/null || echo '(not yet available)')"
echo ""
